#!/usr/bin/env python

import sys, os
currentdir = os.path.dirname(os.path.realpath(__file__))
tests_dir = os.path.dirname(currentdir)
snarl_dir = os.path.dirname(tests_dir)
src_dir = snarl_dir + '/src'
sys.path.append(src_dir)
from controller.controller import parse_level
from model.level import Level

if __name__ == '__main__':
    level_input = sys.stdin.read().strip()
    parsed_input = parse_level(level_input)
    level = parsed_input['level']
    coord = parsed_input['coord']
    info_at_coord = level.info_at_coord(coord)
    print(info_at_coord)
