#!/usr/bin/env python

import sys, os
currentdir = os.path.dirname(os.path.realpath(__file__))
tests_dir = os.path.dirname(currentdir)
snarl_dir = os.path.dirname(tests_dir)
game_dir = snarl_dir + '/src'
sys.path.append(game_dir)
from coord import Coord
from room import Room
from utilities import parse_room

if __name__ == '__main__':
    room_input = sys.stdin.read().strip()
    parse_room(room_input)
