#!/usr/bin/env python

import sys, os
currentdir = os.path.dirname(os.path.realpath(__file__))
tests_dir = os.path.dirname(currentdir)
snarl_dir = os.path.dirname(tests_dir)
src_dir = snarl_dir + '/src'
sys.path.append(src_dir)
from controller.controller import parse_room
from coord import Coord

if __name__ == '__main__':
    room_input = sys.stdin.read().strip()
    parse_room(room_input)
