#!/usr/bin/env python3
import os, sys, argparse
currentdir = os.path.dirname(os.path.realpath(__file__))
snarl_dir = os.path.dirname(currentdir)
src_dir = snarl_dir + '/src'
sys.path.append(src_dir)
from remote.client import Client


parser = argparse.ArgumentParser()
parser.add_argument('-a', '--address', dest='address', action='store', default='127.0.0.1', help='Address to start listing for connections')
parser.add_argument('-p', '--port', dest='port', action='store', type=int, default=45678, help='Port to start listing for connections')


if __name__ == '__main__':
    args = parser.parse_args()
    cl = Client(args.address, args.port)
    cl.run()

